services: # docker compose expects
 app: # custom key name
   # image: python:3.14.2-slim
   build:
     context: .    
     dockerfile: Dockerfile
   ports:
       - 8000:8000
       - 3000:8000 
   command: python -m http.server 8000
