services: # docker compose expects
 static_html: # custom key name
   # image: python:3.14.2-slim
   build:
     context: ./static_html    
     dockerfile: static.Dockerfile
   ports:
       - 8000:8000
       - 3000:8000 
   command: python -m http.server 8000
